call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
echo Building...
cl.exe %*
bt_sample.exe
@REM echo Creating libmedicam.lib...
@REM lib.exe /OUT:libmedicam.lib *.obj
@REM echo Build Test file...
@REM cl.exe test.c /MT /link libmedicam.lib /OUT:test.exe 
@REM echo Testing...
@REM test.exe